/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiprodatabazi_jedensvet;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Properties;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableModel;

/**
 *
 * @author RadimP
 */
public class JFrameJedenSvet extends javax.swing.JFrame {

    ZobrazeniDatTableModel tablemodel_predstaveni_dtb;
    ZobrazeniDatTableModel tablemodel_film_dtb;
    ZobrazeniDatTableModel tablemodel_kino_dtb;
    UpravaDatTableModel empty;
    int case_table;
    ArrayList<ArrayList<Integer>> edited_fields1 = new ArrayList<ArrayList<Integer>>();
    static final String SQLDOTAZ_PREDSTAVENI = "SELECT idPredstaveni, Datum, idFilm FROM jeden_svet.predstaveni;";
    static final String SQLDOTAZ_FILM = "SELECT * FROM jeden_svet.film;";
    static final String SQLDOTAZ_KINO = "SELECT * FROM jeden_svet.kino;";
    static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
    static final String DB_URL = "jdbc:mysql://localhost/jeden_svet";
    Properties properties = new Properties();

    /**
     * Creates new form JFrameJedenSvet
     */
    public JFrameJedenSvet() {
        properties.setProperty("user", "root");
        properties.setProperty("password", "1111");
        properties.setProperty("useSSL", "false");
        properties.setProperty("autoReconnect", "true");
        tablemodel_predstaveni_dtb = new ZobrazeniDatTableModel(SQLDOTAZ_PREDSTAVENI);
        empty = new UpravaDatTableModel();
        initComponents();
        JTableUtilities.setCellsAlignment(jTablePredstaveniDatafromDTB, SwingConstants.CENTER);
        ((DefaultTableCellRenderer) jTablePredstaveniDatafromDTB.getTableHeader().getDefaultRenderer())
                .setHorizontalAlignment(SwingConstants.CENTER);
        ((DefaultTableCellRenderer) jTablePredstaveniZobrazenivybranychDat.getTableHeader().getDefaultRenderer())
                .setHorizontalAlignment(SwingConstants.CENTER);
        JTableUtilities.setColumnWidths(jTablePredstaveniDatafromDTB, 95, 150, 50);
    }

    public void executeStatement(String sql_querry) {
        try {
            Class.forName(JDBC_DRIVER).newInstance();
            Connection connection = DriverManager.getConnection(DB_URL, properties);

            Statement st = connection.createStatement();

            st.execute(sql_querry); //provedení příkazu
            st.closeOnCompletion();
            connection.close();

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException ex) {
            Logger.getLogger(JFrameJedenSvet.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void updateDisplayedData(javax.swing.JTable table, String sql_dotaz) {
        table.setModel(new ZobrazeniDatTableModel(sql_dotaz));
        JTableUtilities.setCellsAlignment(table, SwingConstants.CENTER);
        ((DefaultTableCellRenderer) table.getTableHeader().getDefaultRenderer())
                .setHorizontalAlignment(SwingConstants.CENTER);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTablePredstaveniDatafromDTB = new javax.swing.JTable();
        jButtonPredstaveniVyberData = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTablePredstaveniZobrazenivybranychDat = new javax.swing.JTable();
        jButtonPredstaveniAktualizujVDTB = new javax.swing.JButton();
        jLabelPredstaveniDatavDTB = new javax.swing.JLabel();
        jLabelPredstaveniUpozorneni1 = new javax.swing.JLabel();
        jLabelPredstaveniPopisAktualizace = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTablePredstaveniDatafromDTB.setModel(tablemodel_predstaveni_dtb);
        jTablePredstaveniDatafromDTB.setCellSelectionEnabled(true);
        jScrollPane5.setViewportView(jTablePredstaveniDatafromDTB);

        jButtonPredstaveniVyberData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonPredstaveniVyberData.setText("Vyber označená data");
        jButtonPredstaveniVyberData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPredstaveniVyberDataActionPerformed(evt);
            }
        });

        jTablePredstaveniZobrazenivybranychDat.setModel(empty);
        jTablePredstaveniZobrazenivybranychDat.setCellSelectionEnabled(true);
        jScrollPane6.setViewportView(jTablePredstaveniZobrazenivybranychDat);

        jButtonPredstaveniAktualizujVDTB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonPredstaveniAktualizujVDTB.setText("Aktualizovat v DTB");
        jButtonPredstaveniAktualizujVDTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPredstaveniAktualizujVDTBActionPerformed(evt);
            }
        });

        jLabelPredstaveniDatavDTB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPredstaveniDatavDTB.setText("Tabulka Predstaveni - data v databázi");

        jLabelPredstaveniUpozorneni1.setText("Položku idPredstaveni nelze v databázi přepsat. Položku idFilm lze v databázi přepsat u představení, ale ne v tabulce filmů.");

        jLabelPredstaveniPopisAktualizace.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPredstaveniPopisAktualizace.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPredstaveniPopisAktualizace.setText("Podrobnosti k vybrané položce");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelPredstaveniDatavDTB)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPredstaveniUpozorneni1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPredstaveniVyberData)
                    .addComponent(jLabelPredstaveniPopisAktualizace, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPredstaveniAktualizujVDTB))
                .addGap(241, 241, 241))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPredstaveniDatavDTB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelPredstaveniUpozorneni1)
                .addGap(18, 18, 18)
                .addComponent(jButtonPredstaveniVyberData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabelPredstaveniPopisAktualizace)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPredstaveniAktualizujVDTB)
                .addGap(32, 32, 32))
        );

        jTabbedPane1.addTab("Predstaveni", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Film", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Kino", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(351, 351, 351)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(480, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(365, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPredstaveniVyberDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPredstaveniVyberDataActionPerformed
        int row = jTablePredstaveniDatafromDTB.getSelectedRow();
        int column = jTablePredstaveniDatafromDTB.getSelectedColumn();
        switch (column) {
            case 0:
                case_table = 0;
                String sql0_dotaz = "select predstaveni.idPredstaveni, Datum, predstaveni.idFilm from predstaveni where idPredstaveni=" + "\"" + jTablePredstaveniDatafromDTB.getModel().getValueAt(row, column) + "\"" + ";";

                /* String sql0_dist_dotaz = "select distinct idFilm from film;";
                DataFromDatabase dfd = new DataFromDatabase();
                Vector<Vector<Object>> idfilmu = new Vector<Vector<Object>>();
                idfilmu = dfd.getDataFromSQLDatabase(sql0_dist_dotaz);
                int[] idhodnoty = new int[idfilmu.size()];
                for (int i = 0; i < idfilmu.size(); i++) {
                    idhodnoty[i] = Integer.parseInt(idfilmu.elementAt(i).elementAt(0).toString());
                    
                }*/
                jTablePredstaveniZobrazenivybranychDat.setModel(new UpravaDatTableModel(sql0_dotaz) {
                    @Override //nastavení editovatelnosti data přepsaním typu na string
                    public Class getColumnClass(int column) {
                        for (int row = 0; row < getRowCount(); row++) {
                            if (column == 1) {
                                return String.class;
                            }
                            Object o = getValueAt(row, column);

                            if (o != null && column != 1) {
                                return o.getClass();
                            } else {
                                if (o != null) {
                                    return String.class;
                                }
                            }
                        }

                        return Object.class;
                    }

                    @Override
                    public boolean isCellEditable(int rowIndex, int columnIndex) {
                        if (columnIndex != 1) {
                            return false;
                        } else {
                            return true;
                        }
                    }
                }
                );
                JTableUtilities.setCellsAlignment(jTablePredstaveniZobrazenivybranychDat, SwingConstants.CENTER);
                jLabelPredstaveniPopisAktualizace.setText("V této tabulce můžete upravit datum představení.");
                break;
            case 1:
                case_table = 1;
                String sql1_dotaz = "select film.idFilm, JmenoF, Reziser, Rok, Popis from film inner join predstaveni on predstaveni.idFilm=film.idFilm where predstaveni.Datum=" + "\"" + jTablePredstaveniDatafromDTB.getModel().getValueAt(row, column) + " 00:00:00\"" + ";";
                jTablePredstaveniZobrazenivybranychDat.setModel(new UpravaDatTableModel(sql1_dotaz));
                String datum = jTablePredstaveniDatafromDTB.getModel().getValueAt(row, column).toString();
                JTableUtilities.setCellsAlignment(jTablePredstaveniZobrazenivybranychDat, SwingConstants.CENTER);
                String[] datum1 = datum.split(" ")[0].split(String.valueOf((char) 45));
                jLabelPredstaveniPopisAktualizace.setText(datum1[2] + "." + datum1[1] + "." + datum1[0] + " hrají tyto filmy:");
                break;
            case 2:
                case_table = 2;
                String sql2_dotaz = "select predstaveni.idPredstaveni, film.JmenoF, predstaveni.idFilm from film inner join predstaveni on predstaveni.idFilm=film.idFilm where predstaveni.idFilm =" + "\"" + jTablePredstaveniDatafromDTB.getModel().getValueAt(row, column) + "\"" + ";";
                jTablePredstaveniZobrazenivybranychDat.setModel(new UpravaDatTableModel(sql2_dotaz) {
                    @Override
                    public boolean isCellEditable(int rowIndex, int columnIndex) {
                        if (columnIndex == 0 || columnIndex == 1) {
                            return false;
                        } else {
                            return true;
                        }
                    }
                });
                JTableUtilities.setCellsAlignment(jTablePredstaveniZobrazenivybranychDat, SwingConstants.CENTER);
                jLabelPredstaveniPopisAktualizace.setText("V této tabulce můžete u představení změnit idFilmu.");
            default:
                break;
        }
    }//GEN-LAST:event_jButtonPredstaveniVyberDataActionPerformed

    private void jButtonPredstaveniAktualizujVDTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPredstaveniAktualizujVDTBActionPerformed
        edited_fields1 = ((UpravaDatTableModel) jTablePredstaveniZobrazenivybranychDat.getModel()).getIndexesOfEditedFields();
        System.out.println(edited_fields1);
        System.out.println("kliknuto");
        switch (case_table) {
            case 0:
                for (int i = 0; i < edited_fields1.size(); i++) {
                    String sql_dotaz = "UPDATE predstaveni SET Datum =" + "\"" + jTablePredstaveniZobrazenivybranychDat.getModel().getValueAt(edited_fields1.get(i).get(0), edited_fields1.get(i).get(1)) + " 00:00:00\"" + "WHERE idPredstaveni=" + "\"" + jTablePredstaveniZobrazenivybranychDat.getModel().getValueAt(edited_fields1.get(i).get(0), 0) + "\"" + ";";
                    executeStatement(sql_dotaz);
                    updateDisplayedData(jTablePredstaveniDatafromDTB, SQLDOTAZ_PREDSTAVENI);
                    JTableUtilities.setColumnWidths(jTablePredstaveniDatafromDTB, 95, 150, 50);
                }
                ;
                break;
            default:
                break;
        }

    }//GEN-LAST:event_jButtonPredstaveniAktualizujVDTBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameJedenSvet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameJedenSvet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameJedenSvet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameJedenSvet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JFrameJedenSvet jf = new JFrameJedenSvet();
                jf.pack();
                jf.setLocationRelativeTo(null);
                jf.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPredstaveniAktualizujVDTB;
    private javax.swing.JButton jButtonPredstaveniVyberData;
    private javax.swing.JLabel jLabelPredstaveniDatavDTB;
    private javax.swing.JLabel jLabelPredstaveniPopisAktualizace;
    private javax.swing.JLabel jLabelPredstaveniUpozorneni1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTablePredstaveniDatafromDTB;
    private javax.swing.JTable jTablePredstaveniZobrazenivybranychDat;
    // End of variables declaration//GEN-END:variables
}
