/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiprodatabazi_jedensvet;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import javax.swing.SwingConstants;
import javax.swing.plaf.basic.BasicTabbedPaneUI;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author RadimP
 */
public class JFrameJedenSvet extends javax.swing.JFrame {

    ZobrazeniDatTableModel tablemodel_predstaveni_dtb;
    ZobrazeniDatTableModel tablemodel_film_dtb;
    ZobrazeniDatTableModel tablemodel_kino_dtb;
    PridavaniDatTableModel tablemodel_predstaveni_pridavanidat;
    UpravaDatTableModel emptytable_predstaveni;
    UpravaDatTableModel emptytable_film;
    VyhledavaniDatTableModel emptyresulttable_predstaveni;
    VyhledavaniDatTableModel tablemodel_predstaveni_results;
    int switch_casenumber_predstaveni;
    int predstaveni_popis_filmu_selectedrow_index;
    int predstaveni_popis_filmu_selectedcolumn_index;
    String[] namesofDTBtables = {"predstaveni", "film", "kino"};
    String[] namesofcolumns_predstavenitable = {"idPredstaveni", "Datum", "idFilm"};
    String[] namesofcolumns_filmtable = {"idFilm", "JmenoF", "Reziser", "Rok", "Popis"};
    String[] namesofcolumns_kinotable = {"idKino", "Nazev", "Ulice", "C.popisne", "C.orientacni", "Obec", "PSC", "idPredstaveni"};
    String performed_querry_predstaveni_film_by_date = null;
    String performed_querry_predstaveni_vyhledavani = null;
    ArrayList<ArrayList<Integer>> edited_fields_predstaveni_tab = new ArrayList<ArrayList<Integer>>();
    ArrayList<Integer> edited_rows_predstaveni_tab = new ArrayList<Integer>();
    static final String SQLDOTAZ_PREDSTAVENI = "SELECT idPredstaveni, Datum, idFilm FROM jeden_svet.predstaveni;";
    static final String SQLDOTAZ_FILM = "SELECT * FROM jeden_svet.film;";
    static final String SQLDOTAZ_KINO = "SELECT * FROM jeden_svet.kino;";
    static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
    static final String DB_URL = "jdbc:mysql://localhost/jeden_svet";
    static final Properties properties = new Properties() {
    };

    /**
     * Creates new form JFrameJedenSvet and set properties for connection to
     * Database
     */
    public JFrameJedenSvet() {
        properties.setProperty("user", "root");
        properties.setProperty("password", "1111");
        properties.setProperty("useSSL", "false");
        properties.setProperty("autoReconnect", "true");
        tablemodel_predstaveni_dtb = new ZobrazeniDatTableModel(SQLDOTAZ_PREDSTAVENI, 1);
        tablemodel_predstaveni_pridavanidat = new PridavaniDatTableModel();
        emptytable_predstaveni = new UpravaDatTableModel();
        emptytable_film = new UpravaDatTableModel();
        emptyresulttable_predstaveni = new VyhledavaniDatTableModel(SQLDOTAZ_PREDSTAVENI, "");
        tablemodel_predstaveni_results = new VyhledavaniDatTableModel(SQLDOTAZ_PREDSTAVENI, 1);
        tablemodel_film_dtb = new ZobrazeniDatTableModel(SQLDOTAZ_FILM, 1);
        initComponents();
      jTablePredstaveniZobrazenivybranychDat.setModel(emptytable_predstaveni);
      HelperMethods.setTableCellsAndHeaderCenterHorizontalAlignment(jTableFilmDataFromDTB);
        // HelperMethods.setTableCellsAndHeaderCenterHorizontalAlignment(jTablePredstaveniZobrazenivybranychDat);
        // HelperMethods.setTableCellsAndHeaderCenterHorizontalAlignment(jTablePredstaveniPridaniDat);
        //  HelperMethods.setTableCellsAndHeaderCenterHorizontalAlignment(jTablePredstaveniVysledkyVyhledavani);
        JTableUtilities.setColumnWidths(jTablePredstaveniDatafromDTB, 95, 150, 50);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneSpolecny = new javax.swing.JTabbedPane();
        jPanelPredstaveniHlavni = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTablePredstaveniDatafromDTB = new javax.swing.JTable();
        jTabbedPanePredstaveniVnoreny = new javax.swing.JTabbedPane();
        jPanelPredstaveniUpravaDat = new javax.swing.JPanel();
        jLabelPredstaveniPopisAktualizace = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTablePredstaveniZobrazenivybranychDat = new javax.swing.JTable();
        jButtonPredstaveniAktualizujVDTB = new javax.swing.JButton();
        jButtonPredstaveniUpravitPopis = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaPredstaveniUpravaPopisuFilmu = new javax.swing.JTextArea();
        jLabelPredstaveniUparavaPopisFilmu = new javax.swing.JLabel();
        jButtonPredstaveniUpravenyPopisAktualizovatVDTB = new javax.swing.JButton();
        jButtonPredstaveniPopisFilmuDoTabulky = new javax.swing.JButton();
        jPanelPredstaveniPridavaniDat = new javax.swing.JPanel();
        jLabelPredstaveniPridaniDat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePredstaveniPridaniDat = new javax.swing.JTable();
        jButtonPredstaveniPridatData = new javax.swing.JButton();
        jPanelPredstaveniVyhledavaniDat = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePredstaveniVysledkyVyhledavani = new javax.swing.JTable();
        jLabelPredstaveniVyhledavaniPopisVolby = new javax.swing.JLabel();
        jLabelPredstaveniVyhledavaniVysledky = new javax.swing.JLabel();
        jButtonPredstaveniVyhledavaniidPredstaveniJeMensi = new javax.swing.JButton();
        jButtonPredstaveniVyhledavaniidPredstaveniJeRovno = new javax.swing.JButton();
        jLabelPredstaveniVyhledaniPodleidPredstaveni = new javax.swing.JLabel();
        jButtonPredstaveniVyhledavaniidPredstaveniJeVetsi = new javax.swing.JButton();
        jSpinnerPredstaveniVyhledavaniidPredstaveni = new javax.swing.JSpinner();
        jLabelPredstaverniVyhledavaniDatum = new javax.swing.JLabel();
        jButtonPredstaveniVyhledavaniDatumJeVetsi = new javax.swing.JButton();
        jButtonPredstaveniVyhledavaniDatumJeRovno = new javax.swing.JButton();
        jButtonPredstaveniVyhledavaniDatumJeMensi = new javax.swing.JButton();
        jTextFieldPredstaveniVyhledavaniDatum = new javax.swing.JTextField();
        jLabelPredstaveniVyhledavaniidFilmu = new javax.swing.JLabel();
        jButtonPredstaveniVyhledavaniidFilmuJeVetsi = new javax.swing.JButton();
        jButtonPredstaveniVyhledavaniidFilmuJeRovno = new javax.swing.JButton();
        jButtonPredstaveniVyhledavaniidFilmJeMensi = new javax.swing.JButton();
        jSpinnerPredstaveniVyhledavaniidFilm = new javax.swing.JSpinner();
        jButtonPredstaveniVyhledavavniOdstranitVysledky = new javax.swing.JButton();
        jButtonPredstaveniVyhledavaniVymazatVybraneVysledky = new javax.swing.JButton();
        jLabelPredstaveniDatavDTB = new javax.swing.JLabel();
        jButtonPredstaveniVyberData = new javax.swing.JButton();
        jPanelFilmHlavni = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableFilmDataFromDTB = new javax.swing.JTable();
        jTabbedPaneFilmVnoreny = new javax.swing.JTabbedPane();
        jPanelFilmUpravaDat = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTableFilmZobrazeniVybranychDat = new javax.swing.JTable();
        jLabelFilmPopisAktualizace = new javax.swing.JLabel();
        jButtonFilmAktualizujVDTB = new javax.swing.JButton();
        jPanelFilmPridavaniDat = new javax.swing.JPanel();
        jPanelFilmVyhledavaniDat = new javax.swing.JPanel();
        jLabelFilmDatavDTB = new javax.swing.JLabel();
        jButtonFilmVyberData = new javax.swing.JButton();
        jPanelKinoHlavni = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Databáze Jeden svět");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jTabbedPaneSpolecny.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPaneSpolecny.setUI(new BasicTabbedPaneUI() {
            @Override
            protected void installDefaults() {
                super.installDefaults();
                highlight = Color.LIGHT_GRAY;
                lightHighlight = Color.LIGHT_GRAY;
                shadow = Color.LIGHT_GRAY;
                darkShadow = Color.LIGHT_GRAY;
                focus = Color.LIGHT_GRAY;
            }
        });
        jTabbedPaneSpolecny.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPaneSpolecny.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanelPredstaveniHlavni.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        HelperMethods.setTableCellsAndHeaderCenterHorizontalAlignment(jTablePredstaveniDatafromDTB);
        jTablePredstaveniDatafromDTB.setModel(tablemodel_predstaveni_dtb);
        jTablePredstaveniDatafromDTB.setCellSelectionEnabled(true);
        jTablePredstaveniDatafromDTB.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(jTablePredstaveniDatafromDTB);
        HelperMethods.setTableCellsAndHeaderCenterHorizontalAlignment(jTablePredstaveniDatafromDTB);

        jTabbedPanePredstaveniVnoreny.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPanePredstaveniVnoreny.setUI(new BasicTabbedPaneUI() {
            @Override
            protected void installDefaults() {
                super.installDefaults();
                highlight = Color.LIGHT_GRAY;
                lightHighlight = Color.LIGHT_GRAY;
                shadow = Color.LIGHT_GRAY;
                darkShadow = Color.LIGHT_GRAY;
                focus = Color.LIGHT_GRAY;
            }
        });
        jTabbedPanePredstaveniVnoreny.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPanePredstaveniVnoreny.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTabbedPanePredstaveniVnoreny.setOpaque(true);

        jLabelPredstaveniPopisAktualizace.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPredstaveniPopisAktualizace.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPredstaveniPopisAktualizace.setText("Podrobnosti k vybrané položce");

        jTablePredstaveniZobrazenivybranychDat.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTablePredstaveniZobrazenivybranychDat.setCellSelectionEnabled(true);
        jTablePredstaveniZobrazenivybranychDat.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTablePredstaveniZobrazenivybranychDat.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(jTablePredstaveniZobrazenivybranychDat);

        jButtonPredstaveniAktualizujVDTB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonPredstaveniAktualizujVDTB.setText("Aktualizovat v DTB");
        jButtonPredstaveniAktualizujVDTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPredstaveniAktualizujVDTBActionPerformed(evt);
            }
        });

        jButtonPredstaveniUpravitPopis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonPredstaveniUpravitPopis.setText("Upravit vybraný popis filmu v textovém poli");
        jButtonPredstaveniUpravitPopis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPredstaveniUpravitPopisActionPerformed(evt);
            }
        });

        jTextAreaPredstaveniUpravaPopisuFilmu.setColumns(20);
        jTextAreaPredstaveniUpravaPopisuFilmu.setLineWrap(true);
        jTextAreaPredstaveniUpravaPopisuFilmu.setWrapStyleWord(true);
        jTextAreaPredstaveniUpravaPopisuFilmu.setRows(5);
        jScrollPane3.setViewportView(jTextAreaPredstaveniUpravaPopisuFilmu);

        jLabelPredstaveniUparavaPopisFilmu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPredstaveniUparavaPopisFilmu.setText("Vybraný popis filmu");

        jButtonPredstaveniUpravenyPopisAktualizovatVDTB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonPredstaveniUpravenyPopisAktualizovatVDTB.setText("Aktualizovat popis v DTB");
        jButtonPredstaveniUpravenyPopisAktualizovatVDTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPredstaveniUpravenyPopisAktualizovatVDTBActionPerformed(evt);
            }
        });

        jButtonPredstaveniPopisFilmuDoTabulky.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonPredstaveniPopisFilmuDoTabulky.setText("Uložit popis do tabulky");
        jButtonPredstaveniPopisFilmuDoTabulky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPredstaveniPopisFilmuDoTabulkyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPredstaveniUpravaDatLayout = new javax.swing.GroupLayout(jPanelPredstaveniUpravaDat);
        jPanelPredstaveniUpravaDat.setLayout(jPanelPredstaveniUpravaDatLayout);
        jPanelPredstaveniUpravaDatLayout.setHorizontalGroup(
            jPanelPredstaveniUpravaDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPredstaveniUpravaDatLayout.createSequentialGroup()
                .addGroup(jPanelPredstaveniUpravaDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPredstaveniUpravaDatLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanelPredstaveniUpravaDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabelPredstaveniPopisAktualizace, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelPredstaveniUpravaDatLayout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addGroup(jPanelPredstaveniUpravaDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelPredstaveniUpravaDatLayout.createSequentialGroup()
                                        .addComponent(jButtonPredstaveniUpravenyPopisAktualizovatVDTB)
                                        .addGap(38, 38, 38)
                                        .addComponent(jButtonPredstaveniPopisFilmuDoTabulky))
                                    .addGroup(jPanelPredstaveniUpravaDatLayout.createSequentialGroup()
                                        .addComponent(jButtonPredstaveniAktualizujVDTB)
                                        .addGap(29, 29, 29)
                                        .addComponent(jButtonPredstaveniUpravitPopis))))))
                    .addGroup(jPanelPredstaveniUpravaDatLayout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jLabelPredstaveniUparavaPopisFilmu))
                    .addGroup(jPanelPredstaveniUpravaDatLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanelPredstaveniUpravaDatLayout.setVerticalGroup(
            jPanelPredstaveniUpravaDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPredstaveniUpravaDatLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabelPredstaveniPopisAktualizace)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelPredstaveniUpravaDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPredstaveniAktualizujVDTB)
                    .addComponent(jButtonPredstaveniUpravitPopis))
                .addGap(34, 34, 34)
                .addComponent(jLabelPredstaveniUparavaPopisFilmu)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPredstaveniUpravaDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPredstaveniUpravenyPopisAktualizovatVDTB)
                    .addComponent(jButtonPredstaveniPopisFilmuDoTabulky))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        jTabbedPanePredstaveniVnoreny.addTab("Úprava dat", jPanelPredstaveniUpravaDat);

        jPanelPredstaveniPridavaniDat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelPredstaveniPridaniDat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPredstaveniPridaniDat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPredstaveniPridaniDat.setText("Tabulka pro přidání představení do databáze");

        HelperMethods.setTableCellsAndHeaderCenterHorizontalAlignment(jTablePredstaveniPridaniDat);
        jTablePredstaveniPridaniDat.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTablePredstaveniPridaniDat.setModel(tablemodel_predstaveni_pridavanidat);
        jTablePredstaveniPridaniDat.getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT)
        .put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "selectNextColumnCell");
        jTablePredstaveniPridaniDat.setColumnSelectionAllowed(true);
        jTablePredstaveniPridaniDat.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTablePredstaveniPridaniDat);
        jTablePredstaveniPridaniDat.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jButtonPredstaveniPridatData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonPredstaveniPridatData.setText("Přidat představení do databáze");
        jButtonPredstaveniPridatData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPredstaveniPridatDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPredstaveniPridavaniDatLayout = new javax.swing.GroupLayout(jPanelPredstaveniPridavaniDat);
        jPanelPredstaveniPridavaniDat.setLayout(jPanelPredstaveniPridavaniDatLayout);
        jPanelPredstaveniPridavaniDatLayout.setHorizontalGroup(
            jPanelPredstaveniPridavaniDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPredstaveniPridavaniDatLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanelPredstaveniPridavaniDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelPredstaveniPridaniDat, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPredstaveniPridatData))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanelPredstaveniPridavaniDatLayout.setVerticalGroup(
            jPanelPredstaveniPridavaniDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPredstaveniPridavaniDatLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabelPredstaveniPridaniDat)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jButtonPredstaveniPridatData)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        jTabbedPanePredstaveniVnoreny.addTab("Přidávání dat", jPanelPredstaveniPridavaniDat);

        HelperMethods.setTableCellsAndHeaderCenterHorizontalAlignment(jTablePredstaveniVysledkyVyhledavani);
        jTablePredstaveniVysledkyVyhledavani.setModel(emptyresulttable_predstaveni);
        jTablePredstaveniVysledkyVyhledavani.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jTablePredstaveniVysledkyVyhledavani.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTablePredstaveniVysledkyVyhledavani);

        jLabelPredstaveniVyhledavaniPopisVolby.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPredstaveniVyhledavaniPopisVolby.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPredstaveniVyhledavaniPopisVolby.setText("Vyhledat představení podle:");

        jLabelPredstaveniVyhledavaniVysledky.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPredstaveniVyhledavaniVysledky.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPredstaveniVyhledavaniVysledky.setText("Výsledky vyhledávání:");

        jButtonPredstaveniVyhledavaniidPredstaveniJeMensi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonPredstaveniVyhledavaniidPredstaveniJeMensi.setText("je menší");
        jButtonPredstaveniVyhledavaniidPredstaveniJeMensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPredstaveniVyhledavaniidPredstaveniJeMensiActionPerformed(evt);
            }
        });

        jButtonPredstaveniVyhledavaniidPredstaveniJeRovno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonPredstaveniVyhledavaniidPredstaveniJeRovno.setText("je rovno");
        jButtonPredstaveniVyhledavaniidPredstaveniJeRovno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPredstaveniVyhledavaniidPredstaveniJeRovnoActionPerformed(evt);
            }
        });

        jLabelPredstaveniVyhledaniPodleidPredstaveni.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPredstaveniVyhledaniPodleidPredstaveni.setText("idPredstaveni");

        jButtonPredstaveniVyhledavaniidPredstaveniJeVetsi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonPredstaveniVyhledavaniidPredstaveniJeVetsi.setText("je větší");
        jButtonPredstaveniVyhledavaniidPredstaveniJeVetsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPredstaveniVyhledavaniidPredstaveniJeVetsiActionPerformed(evt);
            }
        });

        jLabelPredstaverniVyhledavaniDatum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPredstaverniVyhledavaniDatum.setText("Datum");

        jButtonPredstaveniVyhledavaniDatumJeVetsi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonPredstaveniVyhledavaniDatumJeVetsi.setText("je větší");
        jButtonPredstaveniVyhledavaniDatumJeVetsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPredstaveniVyhledavaniDatumJeVetsiActionPerformed(evt);
            }
        });

        jButtonPredstaveniVyhledavaniDatumJeRovno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonPredstaveniVyhledavaniDatumJeRovno.setText("je rovno");
        jButtonPredstaveniVyhledavaniDatumJeRovno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPredstaveniVyhledavaniDatumJeRovnoActionPerformed(evt);
            }
        });

        jButtonPredstaveniVyhledavaniDatumJeMensi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonPredstaveniVyhledavaniDatumJeMensi.setText("je menší");
        jButtonPredstaveniVyhledavaniDatumJeMensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPredstaveniVyhledavaniDatumJeMensiActionPerformed(evt);
            }
        });

        jTextFieldPredstaveniVyhledavaniDatum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabelPredstaveniVyhledavaniidFilmu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPredstaveniVyhledavaniidFilmu.setText("idFilmu");

        jButtonPredstaveniVyhledavaniidFilmuJeVetsi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonPredstaveniVyhledavaniidFilmuJeVetsi.setText("je větší");
        jButtonPredstaveniVyhledavaniidFilmuJeVetsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPredstaveniVyhledavaniidFilmuJeVetsiActionPerformed(evt);
            }
        });

        jButtonPredstaveniVyhledavaniidFilmuJeRovno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonPredstaveniVyhledavaniidFilmuJeRovno.setText("je rovno");
        jButtonPredstaveniVyhledavaniidFilmuJeRovno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPredstaveniVyhledavaniidFilmuJeRovnoActionPerformed(evt);
            }
        });

        jButtonPredstaveniVyhledavaniidFilmJeMensi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonPredstaveniVyhledavaniidFilmJeMensi.setText("je menší");
        jButtonPredstaveniVyhledavaniidFilmJeMensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPredstaveniVyhledavaniidFilmJeMensiActionPerformed(evt);
            }
        });

        jSpinnerPredstaveniVyhledavaniidFilm.setMinimumSize(new java.awt.Dimension(50, 20));

        jButtonPredstaveniVyhledavavniOdstranitVysledky.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonPredstaveniVyhledavavniOdstranitVysledky.setText("Vyprázdnit tabulku výsledků");
        jButtonPredstaveniVyhledavavniOdstranitVysledky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPredstaveniVyhledavavniOdstranitVysledkyActionPerformed(evt);
            }
        });

        jButtonPredstaveniVyhledavaniVymazatVybraneVysledky.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonPredstaveniVyhledavaniVymazatVybraneVysledky.setText("Vymazat vybrané výsledky");
        jButtonPredstaveniVyhledavaniVymazatVybraneVysledky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPredstaveniVyhledavaniVymazatVybraneVysledkyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPredstaveniVyhledavaniDatLayout = new javax.swing.GroupLayout(jPanelPredstaveniVyhledavaniDat);
        jPanelPredstaveniVyhledavaniDat.setLayout(jPanelPredstaveniVyhledavaniDatLayout);
        jPanelPredstaveniVyhledavaniDatLayout.setHorizontalGroup(
            jPanelPredstaveniVyhledavaniDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPredstaveniVyhledavaniDatLayout.createSequentialGroup()
                .addGroup(jPanelPredstaveniVyhledavaniDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPredstaveniVyhledavaniDatLayout.createSequentialGroup()
                        .addGap(373, 373, 373)
                        .addComponent(jSpinnerPredstaveniVyhledavaniidFilm, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                        .addGap(147, 147, 147))
                    .addGroup(jPanelPredstaveniVyhledavaniDatLayout.createSequentialGroup()
                        .addGroup(jPanelPredstaveniVyhledavaniDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPredstaveniVyhledavaniDatLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelPredstaveniVyhledavaniPopisVolby, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelPredstaveniVyhledavaniDatLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(jPanelPredstaveniVyhledavaniDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPredstaveniVyhledaniPodleidPredstaveni)
                                    .addGroup(jPanelPredstaveniVyhledavaniDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelPredstaveniVyhledavaniidFilmu)
                                        .addComponent(jLabelPredstaverniVyhledavaniDatum)))))
                        .addGap(44, 44, 44)
                        .addGroup(jPanelPredstaveniVyhledavaniDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonPredstaveniVyhledavaniidFilmJeMensi)
                            .addGroup(jPanelPredstaveniVyhledavaniDatLayout.createSequentialGroup()
                                .addGroup(jPanelPredstaveniVyhledavaniDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonPredstaveniVyhledavaniDatumJeRovno)
                                    .addComponent(jButtonPredstaveniVyhledavaniidPredstaveniJeRovno)
                                    .addComponent(jButtonPredstaveniVyhledavaniidPredstaveniJeVetsi, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonPredstaveniVyhledavaniidPredstaveniJeMensi, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonPredstaveniVyhledavaniDatumJeVetsi, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonPredstaveniVyhledavaniDatumJeMensi, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonPredstaveniVyhledavaniidFilmuJeVetsi, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonPredstaveniVyhledavaniidFilmuJeRovno))
                                .addGap(49, 49, 49)
                                .addGroup(jPanelPredstaveniVyhledavaniDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelPredstaveniVyhledavaniDatLayout.createSequentialGroup()
                                        .addComponent(jSpinnerPredstaveniVyhledavaniidPredstaveni)
                                        .addGap(69, 69, 69))
                                    .addComponent(jTextFieldPredstaveniVyhledavaniDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(86, 86, 86))
                    .addGroup(jPanelPredstaveniVyhledavaniDatLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanelPredstaveniVyhledavaniDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPredstaveniVyhledavaniDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(jLabelPredstaveniVyhledavaniVysledky, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelPredstaveniVyhledavaniDatLayout.createSequentialGroup()
                                .addComponent(jButtonPredstaveniVyhledavavniOdstranitVysledky)
                                .addGap(54, 54, 54)
                                .addComponent(jButtonPredstaveniVyhledavaniVymazatVybraneVysledky)))))
                .addGap(84, 84, 84))
        );

        jPanelPredstaveniVyhledavaniDatLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonPredstaveniVyhledavaniDatumJeMensi, jButtonPredstaveniVyhledavaniDatumJeRovno, jButtonPredstaveniVyhledavaniDatumJeVetsi, jButtonPredstaveniVyhledavaniidFilmJeMensi, jButtonPredstaveniVyhledavaniidFilmuJeRovno, jButtonPredstaveniVyhledavaniidFilmuJeVetsi, jButtonPredstaveniVyhledavaniidPredstaveniJeMensi, jButtonPredstaveniVyhledavaniidPredstaveniJeRovno, jButtonPredstaveniVyhledavaniidPredstaveniJeVetsi});

        jPanelPredstaveniVyhledavaniDatLayout.setVerticalGroup(
            jPanelPredstaveniVyhledavaniDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPredstaveniVyhledavaniDatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPredstaveniVyhledavaniDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPredstaveniVyhledavaniDatLayout.createSequentialGroup()
                        .addComponent(jLabelPredstaveniVyhledavaniPopisVolby)
                        .addGroup(jPanelPredstaveniVyhledavaniDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelPredstaveniVyhledavaniDatLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jSpinnerPredstaveniVyhledavaniidPredstaveni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPredstaveniVyhledavaniDatLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelPredstaveniVyhledaniPodleidPredstaveni))))
                    .addGroup(jPanelPredstaveniVyhledavaniDatLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jButtonPredstaveniVyhledavaniidPredstaveniJeVetsi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPredstaveniVyhledavaniidPredstaveniJeRovno)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPredstaveniVyhledavaniidPredstaveniJeMensi)
                .addGap(23, 23, 23)
                .addComponent(jButtonPredstaveniVyhledavaniDatumJeVetsi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPredstaveniVyhledavaniDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPredstaveniVyhledavaniDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPredstaverniVyhledavaniDatum)
                    .addComponent(jButtonPredstaveniVyhledavaniDatumJeRovno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPredstaveniVyhledavaniDatumJeMensi)
                .addGap(26, 26, 26)
                .addComponent(jButtonPredstaveniVyhledavaniidFilmuJeVetsi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPredstaveniVyhledavaniDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelPredstaveniVyhledavaniDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonPredstaveniVyhledavaniidFilmuJeRovno)
                        .addComponent(jSpinnerPredstaveniVyhledavaniidFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelPredstaveniVyhledavaniidFilmu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPredstaveniVyhledavaniidFilmJeMensi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabelPredstaveniVyhledavaniVysledky)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPredstaveniVyhledavaniDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPredstaveniVyhledavavniOdstranitVysledky)
                    .addComponent(jButtonPredstaveniVyhledavaniVymazatVybraneVysledky))
                .addGap(17, 17, 17))
        );

        jTabbedPanePredstaveniVnoreny.addTab("Vyhledávání", jPanelPredstaveniVyhledavaniDat);

        jLabelPredstaveniDatavDTB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPredstaveniDatavDTB.setText("Tabulka Predstaveni - data v databázi");

        jButtonPredstaveniVyberData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonPredstaveniVyberData.setText("Vyber označená data");
        jButtonPredstaveniVyberData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPredstaveniVyberDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPredstaveniHlavniLayout = new javax.swing.GroupLayout(jPanelPredstaveniHlavni);
        jPanelPredstaveniHlavni.setLayout(jPanelPredstaveniHlavniLayout);
        jPanelPredstaveniHlavniLayout.setHorizontalGroup(
            jPanelPredstaveniHlavniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPredstaveniHlavniLayout.createSequentialGroup()
                .addContainerGap(228, Short.MAX_VALUE)
                .addGroup(jPanelPredstaveniHlavniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelPredstaveniDatavDTB)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPredstaveniVyberData)
                    .addComponent(jTabbedPanePredstaveniVnoreny, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        jPanelPredstaveniHlavniLayout.setVerticalGroup(
            jPanelPredstaveniHlavniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPredstaveniHlavniLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabelPredstaveniDatavDTB)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPredstaveniVyberData)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPanePredstaveniVnoreny, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPaneSpolecny.addTab("Predstaveni", jPanelPredstaveniHlavni);

        jPanelFilmHlavni.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTableFilmDataFromDTB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableFilmDataFromDTB.setModel(tablemodel_film_dtb);
        jTableFilmDataFromDTB.setCellSelectionEnabled(true);
        jTableFilmDataFromDTB.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableFilmDataFromDTB.getTableHeader().setReorderingAllowed(false);
        HelperMethods.setTableCellsAndHeaderCenterHorizontalAlignment(jTablePredstaveniDatafromDTB);
        jScrollPane4.setViewportView(jTableFilmDataFromDTB);

        jTabbedPaneFilmVnoreny.setUI(new BasicTabbedPaneUI() {
            @Override
            protected void installDefaults() {
                super.installDefaults();
                highlight = Color.LIGHT_GRAY;
                lightHighlight = Color.LIGHT_GRAY;
                shadow = Color.LIGHT_GRAY;
                darkShadow = Color.LIGHT_GRAY;
                focus = Color.LIGHT_GRAY;
            }
        });
        jTabbedPaneFilmVnoreny.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPaneFilmVnoreny.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPaneFilmVnoreny.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTableFilmZobrazeniVybranychDat.setModel(emptytable_film);
        jScrollPane7.setViewportView(jTableFilmZobrazeniVybranychDat);

        jLabelFilmPopisAktualizace.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelFilmPopisAktualizace.setText("Popis k vybrané položce");

        jButtonFilmAktualizujVDTB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonFilmAktualizujVDTB.setText("Aktualizovat v DTB");

        javax.swing.GroupLayout jPanelFilmUpravaDatLayout = new javax.swing.GroupLayout(jPanelFilmUpravaDat);
        jPanelFilmUpravaDat.setLayout(jPanelFilmUpravaDatLayout);
        jPanelFilmUpravaDatLayout.setHorizontalGroup(
            jPanelFilmUpravaDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilmUpravaDatLayout.createSequentialGroup()
                .addGroup(jPanelFilmUpravaDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFilmUpravaDatLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(jPanelFilmUpravaDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFilmPopisAktualizace)))
                    .addGroup(jPanelFilmUpravaDatLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jButtonFilmAktualizujVDTB)))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jPanelFilmUpravaDatLayout.setVerticalGroup(
            jPanelFilmUpravaDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilmUpravaDatLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelFilmPopisAktualizace)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonFilmAktualizujVDTB)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        jTabbedPaneFilmVnoreny.addTab("Úprava dat", jPanelFilmUpravaDat);

        javax.swing.GroupLayout jPanelFilmPridavaniDatLayout = new javax.swing.GroupLayout(jPanelFilmPridavaniDat);
        jPanelFilmPridavaniDat.setLayout(jPanelFilmPridavaniDatLayout);
        jPanelFilmPridavaniDatLayout.setHorizontalGroup(
            jPanelFilmPridavaniDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 773, Short.MAX_VALUE)
        );
        jPanelFilmPridavaniDatLayout.setVerticalGroup(
            jPanelFilmPridavaniDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );

        jTabbedPaneFilmVnoreny.addTab("Přidávání filmů", jPanelFilmPridavaniDat);

        javax.swing.GroupLayout jPanelFilmVyhledavaniDatLayout = new javax.swing.GroupLayout(jPanelFilmVyhledavaniDat);
        jPanelFilmVyhledavaniDat.setLayout(jPanelFilmVyhledavaniDatLayout);
        jPanelFilmVyhledavaniDatLayout.setHorizontalGroup(
            jPanelFilmVyhledavaniDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 773, Short.MAX_VALUE)
        );
        jPanelFilmVyhledavaniDatLayout.setVerticalGroup(
            jPanelFilmVyhledavaniDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );

        jTabbedPaneFilmVnoreny.addTab("Vyhledávání filmů", jPanelFilmVyhledavaniDat);

        jLabelFilmDatavDTB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelFilmDatavDTB.setText("Tabulka Film - data v databázi");

        jButtonFilmVyberData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonFilmVyberData.setText("Vyber označená data");

        javax.swing.GroupLayout jPanelFilmHlavniLayout = new javax.swing.GroupLayout(jPanelFilmHlavni);
        jPanelFilmHlavni.setLayout(jPanelFilmHlavniLayout);
        jPanelFilmHlavniLayout.setHorizontalGroup(
            jPanelFilmHlavniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilmHlavniLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelFilmHlavniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelFilmDatavDTB)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFilmVyberData))
                .addGap(313, 313, 313))
            .addGroup(jPanelFilmHlavniLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jTabbedPaneFilmVnoreny, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
        );
        jPanelFilmHlavniLayout.setVerticalGroup(
            jPanelFilmHlavniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilmHlavniLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabelFilmDatavDTB)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButtonFilmVyberData)
                .addGap(66, 66, 66)
                .addComponent(jTabbedPaneFilmVnoreny, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPaneSpolecny.addTab("Film", jPanelFilmHlavni);

        jPanelKinoHlavni.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanelKinoHlavniLayout = new javax.swing.GroupLayout(jPanelKinoHlavni);
        jPanelKinoHlavni.setLayout(jPanelKinoHlavniLayout);
        jPanelKinoHlavniLayout.setHorizontalGroup(
            jPanelKinoHlavniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1101, Short.MAX_VALUE)
        );
        jPanelKinoHlavniLayout.setVerticalGroup(
            jPanelKinoHlavniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 804, Short.MAX_VALUE)
        );

        jTabbedPaneSpolecny.addTab("Kino", jPanelKinoHlavni);

        getContentPane().add(jTabbedPaneSpolecny);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButtonPredstaveniVyberDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPredstaveniVyberDataActionPerformed
        int row = jTablePredstaveniDatafromDTB.getSelectedRow();
        int column = jTablePredstaveniDatafromDTB.getSelectedColumn();
        switch (column) {

            case 0:
                switch_casenumber_predstaveni = 0;
                String sql0_dotaz = PrepareStatement.selectDatabySelectedValue(namesofcolumns_predstavenitable, namesofDTBtables[0], namesofcolumns_predstavenitable[0], jTablePredstaveniDatafromDTB.getModel().getValueAt(row, column));
                                               
                jTablePredstaveniZobrazenivybranychDat.setModel(new UpravaDatTableModel(sql0_dotaz, 1) {
                    @Override //nastavení editovatelnosti data přepsaním typu na string
                    public Class getColumnClass(int column) {
                        for (int row = 0; row < getRowCount(); row++) {
                            Object o = getValueAt(row, column);
                            if (o != null && column != 1) {
                                return o.getClass();
                            } else {
                                if (o != null) {
                                    return String.class;
                                }
                            }
                        }

                        return Object.class;
                    }

                    @Override
                    public boolean isCellEditable(int rowIndex, int columnIndex) {
                        return columnIndex == 1;
                    }
                }
                );
                JTableUtilities.setCellsAlignment(jTablePredstaveniZobrazenivybranychDat, SwingConstants.CENTER);
                jLabelPredstaveniPopisAktualizace.setText("V této tabulce můžete upravit datum představení.");
                break;

            case 1:

                switch_casenumber_predstaveni = 1;
                String sql1_dotaz = PrepareStatement.selectDatabySelectedValueUsingOneInnerJoin(namesofcolumns_filmtable, namesofDTBtables[1], namesofDTBtables[0],
                        namesofcolumns_filmtable[0], namesofcolumns_predstavenitable[2], namesofcolumns_predstavenitable[1], jTablePredstaveniDatafromDTB.getModel().getValueAt(row, column));
               /* String sql1_dotaz = "select film.idFilm, JmenoF, Reziser, Rok, Popis from film inner join predstaveni on predstaveni.idFilm=film.idFilm where predstaveni.Datum="
                        + "\"" + HelperMethods.convertDateStringWithPointsToDatabaseFormat(jTablePredstaveniDatafromDTB.getModel().getValueAt(row, column).toString()) + "\"" + ";";
                System.out.println(sql1_dotaz);*/
                performed_querry_predstaveni_film_by_date = sql1_dotaz;
                jTablePredstaveniZobrazenivybranychDat.setModel(new UpravaDatTableModel(sql1_dotaz, 1));
                JTableUtilities.setCellsAlignment(jTablePredstaveniZobrazenivybranychDat, SwingConstants.CENTER);
                String datum = jTablePredstaveniDatafromDTB.getModel().getValueAt(row, column).toString();
                jLabelPredstaveniPopisAktualizace.setText(datum + " hrají tyto filmy:");
                break;

            case 2:

                switch_casenumber_predstaveni = 2;
                String sql2_dotaz = "select predstaveni.idPredstaveni, film.JmenoF, predstaveni.idFilm from film inner join predstaveni on predstaveni.idFilm=film.idFilm where predstaveni.idFilm ="
                        + "\"" + jTablePredstaveniDatafromDTB.getModel().getValueAt(row, column) + "\"" + ";";
                jTablePredstaveniZobrazenivybranychDat.setModel(new UpravaDatTableModel(sql2_dotaz, 1) {
                    @Override
                    public boolean isCellEditable(int rowIndex, int columnIndex) {
                        return !(columnIndex == 0 || columnIndex == 1);
                    }
                });                
                HelperMethods.setTableCellsAndHeaderCenterHorizontalAlignment(jTablePredstaveniZobrazenivybranychDat);
                jLabelPredstaveniPopisAktualizace.setText("V této tabulce můžete u představení změnit idFilmu.");
            default:
                break;
        }
    }//GEN-LAST:event_jButtonPredstaveniVyberDataActionPerformed

    private void executeStatement(String sql_querry) {
        try {
            Class.forName(JDBC_DRIVER).newInstance();
            try (Connection connection = DriverManager.getConnection(DB_URL, properties)) {
                Statement st = connection.createStatement();
                st.execute(sql_querry);
                st.closeOnCompletion();
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException ex) {
            Logger.getLogger(JFrameJedenSvet.class.getName()).log(Level.SEVERE, null, ex);
        }

    }


    private void jButtonPredstaveniAktualizujVDTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPredstaveniAktualizujVDTBActionPerformed
        edited_fields_predstaveni_tab = ((UpravaDatTableModel) jTablePredstaveniZobrazenivybranychDat.getModel()).getIndicesOfEditedFields();

        switch (switch_casenumber_predstaveni) {

            case 0:
                for (int i = 0; i < edited_fields_predstaveni_tab.size(); i++) {
                    
                    String sql_dotaz = PrepareStatement.updateEditedValueInDTB(namesofDTBtables[0], namesofcolumns_predstavenitable[1],
                    jTablePredstaveniZobrazenivybranychDat.getModel().getValueAt(edited_fields_predstaveni_tab.get(i).get(0),
                    edited_fields_predstaveni_tab.get(i).get(1)), namesofcolumns_predstavenitable[0],
                    jTablePredstaveniZobrazenivybranychDat.getModel().getValueAt(edited_fields_predstaveni_tab.get(i).get(0), 0));
                    
                    executeStatement(sql_dotaz);
                }
                HelperMethods.updateDisplayedDataInTableWithZobrazeniDatTableModel(jTablePredstaveniDatafromDTB, SQLDOTAZ_PREDSTAVENI);
                break;

            case 1:
                for (int i = 0; i < edited_fields_predstaveni_tab.size(); i++) {
                    String columnname = jTablePredstaveniZobrazenivybranychDat.getModel().getColumnName(edited_fields_predstaveni_tab.get(i).get(1));
                    
                    String sql_dotaz = PrepareStatement.updateEditedValueInDTB(namesofDTBtables[1], columnname,
                    jTablePredstaveniZobrazenivybranychDat.getModel().getValueAt(edited_fields_predstaveni_tab.get(i).get(0),
                    edited_fields_predstaveni_tab.get(i).get(1)), namesofcolumns_filmtable[0],
                    jTablePredstaveniZobrazenivybranychDat.getModel().getValueAt(edited_fields_predstaveni_tab.get(i).get(0), 0));
                    
                    executeStatement(sql_dotaz);
                }
                HelperMethods.updateDisplayedDataInTableWithZobrazeniDatTableModel(jTablePredstaveniDatafromDTB, SQLDOTAZ_PREDSTAVENI);
                break;

            case 2:
                for (int i = 0; i < edited_fields_predstaveni_tab.size(); i++) {
                    
                    String sql_dotaz_test = PrepareStatement.updateEditedValueInDTB(namesofDTBtables[0], namesofcolumns_predstavenitable[2], jTablePredstaveniZobrazenivybranychDat.getModel().getValueAt(edited_fields_predstaveni_tab.get(i).get(0), edited_fields_predstaveni_tab.get(i).get(1)), namesofcolumns_predstavenitable[2], jTablePredstaveniZobrazenivybranychDat.getModel().getValueAt(edited_fields_predstaveni_tab.get(i).get(0), 0));
                    
                    String sql_dotaz = "UPDATE predstaveni SET predstaveni.idFilm =" + "\"" + jTablePredstaveniZobrazenivybranychDat.getModel().getValueAt(edited_fields_predstaveni_tab.get(i).get(0), edited_fields_predstaveni_tab.get(i).get(1)) + "\"" + "WHERE idPredstaveni=" + "\"" + jTablePredstaveniZobrazenivybranychDat.getModel().getValueAt(edited_fields_predstaveni_tab.get(i).get(0), 0) + "\"" + ";";
                    System.out.println(sql_dotaz_test);
                    executeStatement(sql_dotaz_test);
                }
                HelperMethods.updateDisplayedDataInTableWithZobrazeniDatTableModel(jTablePredstaveniDatafromDTB, SQLDOTAZ_PREDSTAVENI);
                //  JTableUtilities.setColumnWidths(jTablePredstaveniDatafromDTB, 95, 150, 50);
                break;

            default:
                break;
        }

    }//GEN-LAST:event_jButtonPredstaveniAktualizujVDTBActionPerformed
    private ArrayList<Integer> getDistinctIndicesOfEditedRows() {
        edited_rows_predstaveni_tab = ((PridavaniDatTableModel) jTablePredstaveniPridaniDat.getModel()).getIndicesOfEditedRows();
        ArrayList<Integer> distinctIndices = new ArrayList<Integer>(new HashSet<>(edited_rows_predstaveni_tab));
        return distinctIndices;
    }
    
    private void jButtonPredstaveniPridatDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPredstaveniPridatDataActionPerformed
        edited_rows_predstaveni_tab = getDistinctIndicesOfEditedRows();
        for (int i = 0; i < edited_rows_predstaveni_tab.size(); i++) {

            String sql_dotaz = "INSERT INTO predstaveni (Datum, idFilm) values ('" + HelperMethods.convertDateStringWithPointsToDatabaseFormat(jTablePredstaveniPridaniDat.getModel().getValueAt(edited_rows_predstaveni_tab.get(i), 1).toString())
                    + "', " + "'" + jTablePredstaveniPridaniDat.getModel().getValueAt(edited_rows_predstaveni_tab.get(i), 2) + "');";
            executeStatement(sql_dotaz);

            HelperMethods.updateDisplayedDataInTableWithZobrazeniDatTableModel(jTablePredstaveniDatafromDTB, SQLDOTAZ_PREDSTAVENI);
            //.setColumnWidths(jTablePredstaveniDatafromDTB, 95, 150, 50);
            
        }
        jTablePredstaveniPridaniDat.setModel(new PridavaniDatTableModel());
    }//GEN-LAST:event_jButtonPredstaveniPridatDataActionPerformed

    
    private void jButtonPredstaveniVyhledavaniidPredstaveniJeRovnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPredstaveniVyhledavaniidPredstaveniJeRovnoActionPerformed
        performed_querry_predstaveni_vyhledavani = null;
        String sqlidPredstaveni_equals = PrepareStatement.SearchDataFullfilingQuantitativeRelation(namesofcolumns_predstavenitable, namesofDTBtables[0], namesofcolumns_predstavenitable[0], "=", jSpinnerPredstaveniVyhledavaniidPredstaveni.getValue());
        
        System.out.println(sqlidPredstaveni_equals);
        HelperMethods.updateTableWithVyhledavaniDatTableModel(jTablePredstaveniVysledkyVyhledavani, sqlidPredstaveni_equals);
        //  jTablePredstaveniVysledkyVyhledavani.setModel(new VyhledavaniDatTableModel(sqlidPredstaveni_equals, 1));
        //  JTableUtilities.setCellsAlignment(jTablePredstaveniVysledkyVyhledavani, SwingConstants.CENTER);
        performed_querry_predstaveni_vyhledavani = sqlidPredstaveni_equals;
    }//GEN-LAST:event_jButtonPredstaveniVyhledavaniidPredstaveniJeRovnoActionPerformed

    private void jButtonPredstaveniVyhledavaniDatumJeRovnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPredstaveniVyhledavaniDatumJeRovnoActionPerformed
        performed_querry_predstaveni_vyhledavani = null;
         String sqldate_equals = PrepareStatement.SearchDataFullfilingQuantitativeRelation(namesofcolumns_predstavenitable, namesofDTBtables[0], namesofcolumns_predstavenitable[1], "=", jTextFieldPredstaveniVyhledavaniDatum.getText());
        
        System.out.println(sqldate_equals);
        HelperMethods.updateTableWithVyhledavaniDatTableModel(jTablePredstaveniVysledkyVyhledavani, sqldate_equals);
        //  jTablePredstaveniVysledkyVyhledavani.setModel(new VyhledavaniDatTableModel(sqldate_equals, 1));
        //  JTableUtilities.setCellsAlignment(jTablePredstaveniVysledkyVyhledavani, SwingConstants.CENTER);
        performed_querry_predstaveni_vyhledavani = sqldate_equals;
    }//GEN-LAST:event_jButtonPredstaveniVyhledavaniDatumJeRovnoActionPerformed

    private void jButtonPredstaveniVyhledavaniDatumJeVetsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPredstaveniVyhledavaniDatumJeVetsiActionPerformed
        performed_querry_predstaveni_vyhledavani = null;
        String sqldate_more = PrepareStatement.SearchDataFullfilingQuantitativeRelation(namesofcolumns_predstavenitable, namesofDTBtables[0], namesofcolumns_predstavenitable[1], ">", jTextFieldPredstaveniVyhledavaniDatum.getText());
        System.out.println(sqldate_more);
        HelperMethods.updateTableWithVyhledavaniDatTableModel(jTablePredstaveniVysledkyVyhledavani, sqldate_more);
        //  jTablePredstaveniVysledkyVyhledavani.setModel(new VyhledavaniDatTableModel(sqldate_more, 1));
        // JTableUtilities.setCellsAlignment(jTablePredstaveniVysledkyVyhledavani, SwingConstants.CENTER);
        performed_querry_predstaveni_vyhledavani = sqldate_more;
    }//GEN-LAST:event_jButtonPredstaveniVyhledavaniDatumJeVetsiActionPerformed

    private void jButtonPredstaveniVyhledavaniDatumJeMensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPredstaveniVyhledavaniDatumJeMensiActionPerformed
        performed_querry_predstaveni_vyhledavani = null;
        String sqldate_less = PrepareStatement.SearchDataFullfilingQuantitativeRelation(namesofcolumns_predstavenitable, namesofDTBtables[0], namesofcolumns_predstavenitable[1], "<", jTextFieldPredstaveniVyhledavaniDatum.getText());
        System.out.println(sqldate_less);
        HelperMethods.updateTableWithVyhledavaniDatTableModel(jTablePredstaveniVysledkyVyhledavani, sqldate_less);
        //  jTablePredstaveniVysledkyVyhledavani.setModel(new VyhledavaniDatTableModel(sqldate_less, 1));
        //  JTableUtilities.setCellsAlignment(jTablePredstaveniVysledkyVyhledavani, SwingConstants.CENTER);
        performed_querry_predstaveni_vyhledavani = sqldate_less;
    }//GEN-LAST:event_jButtonPredstaveniVyhledavaniDatumJeMensiActionPerformed

    private void jButtonPredstaveniVyhledavaniidPredstaveniJeVetsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPredstaveniVyhledavaniidPredstaveniJeVetsiActionPerformed
        performed_querry_predstaveni_vyhledavani = null;
        String sqlidPredstaveni_more = PrepareStatement.SearchDataFullfilingQuantitativeRelation(namesofcolumns_predstavenitable, namesofDTBtables[0], namesofcolumns_predstavenitable[0], ">", jSpinnerPredstaveniVyhledavaniidPredstaveni.getValue());
        System.out.println(sqlidPredstaveni_more);
        HelperMethods.updateTableWithVyhledavaniDatTableModel(jTablePredstaveniVysledkyVyhledavani, sqlidPredstaveni_more);
        // jTablePredstaveniVysledkyVyhledavani.setModel(new VyhledavaniDatTableModel(sqlidPredstaveni_more, 1));
        // JTableUtilities.setCellsAlignment(jTablePredstaveniVysledkyVyhledavani, SwingConstants.CENTER);
        performed_querry_predstaveni_vyhledavani = sqlidPredstaveni_more;
    }//GEN-LAST:event_jButtonPredstaveniVyhledavaniidPredstaveniJeVetsiActionPerformed

    private void jButtonPredstaveniVyhledavaniidPredstaveniJeMensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPredstaveniVyhledavaniidPredstaveniJeMensiActionPerformed
        performed_querry_predstaveni_vyhledavani = null;
        String sqlidPredstaveni_less = PrepareStatement.SearchDataFullfilingQuantitativeRelation(namesofcolumns_predstavenitable, namesofDTBtables[0], namesofcolumns_predstavenitable[0], "<", jSpinnerPredstaveniVyhledavaniidPredstaveni.getValue());
        System.out.println(sqlidPredstaveni_less);
        HelperMethods.updateTableWithVyhledavaniDatTableModel(jTablePredstaveniVysledkyVyhledavani, sqlidPredstaveni_less);
        //  jTablePredstaveniVysledkyVyhledavani.setModel(new VyhledavaniDatTableModel(sqlidPredstaveni_less, 1));
        //  JTableUtilities.setCellsAlignment(jTablePredstaveniVysledkyVyhledavani, SwingConstants.CENTER);
        performed_querry_predstaveni_vyhledavani = sqlidPredstaveni_less;
    }//GEN-LAST:event_jButtonPredstaveniVyhledavaniidPredstaveniJeMensiActionPerformed

    private void jButtonPredstaveniVyhledavaniidFilmuJeVetsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPredstaveniVyhledavaniidFilmuJeVetsiActionPerformed
        performed_querry_predstaveni_vyhledavani = null;
        String sqlidFilm_more = PrepareStatement.SearchDataFullfilingQuantitativeRelation(namesofcolumns_predstavenitable, namesofDTBtables[0], namesofcolumns_predstavenitable[2], ">", jSpinnerPredstaveniVyhledavaniidFilm.getValue());
               
        System.out.println(sqlidFilm_more);
        HelperMethods.updateTableWithVyhledavaniDatTableModel(jTablePredstaveniVysledkyVyhledavani, sqlidFilm_more);
        // jTablePredstaveniVysledkyVyhledavani.setModel(new VyhledavaniDatTableModel(sqlidFilm_more, 1));
        // JTableUtilities.setCellsAlignment(jTablePredstaveniVysledkyVyhledavani, SwingConstants.CENTER);
        performed_querry_predstaveni_vyhledavani = sqlidFilm_more;
    }//GEN-LAST:event_jButtonPredstaveniVyhledavaniidFilmuJeVetsiActionPerformed

    private void jButtonPredstaveniVyhledavaniidFilmuJeRovnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPredstaveniVyhledavaniidFilmuJeRovnoActionPerformed
        performed_querry_predstaveni_vyhledavani = null;
        String sqlidFilm_equals = PrepareStatement.SearchDataFullfilingQuantitativeRelation(namesofcolumns_predstavenitable, namesofDTBtables[0], namesofcolumns_predstavenitable[2], "=", jSpinnerPredstaveniVyhledavaniidFilm.getValue());
        System.out.println(sqlidFilm_equals);
        HelperMethods.updateTableWithVyhledavaniDatTableModel(jTablePredstaveniVysledkyVyhledavani, sqlidFilm_equals);
        // jTablePredstaveniVysledkyVyhledavani.setModel(new VyhledavaniDatTableModel(sqlidFilm_equals, 1));
        //  JTableUtilities.setCellsAlignment(jTablePredstaveniVysledkyVyhledavani, SwingConstants.CENTER);
        performed_querry_predstaveni_vyhledavani = sqlidFilm_equals;
    }//GEN-LAST:event_jButtonPredstaveniVyhledavaniidFilmuJeRovnoActionPerformed

    private void jButtonPredstaveniVyhledavaniidFilmJeMensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPredstaveniVyhledavaniidFilmJeMensiActionPerformed
        performed_querry_predstaveni_vyhledavani = null;
        String sqlidFilm_less = PrepareStatement.SearchDataFullfilingQuantitativeRelation(namesofcolumns_predstavenitable, namesofDTBtables[0], namesofcolumns_predstavenitable[2], "<", jSpinnerPredstaveniVyhledavaniidFilm.getValue());
        System.out.println(sqlidFilm_less);
        HelperMethods.updateTableWithVyhledavaniDatTableModel(jTablePredstaveniVysledkyVyhledavani, sqlidFilm_less);
        // jTablePredstaveniVysledkyVyhledavani.setModel(new VyhledavaniDatTableModel(sqlidFilm_less, 1));
        // JTableUtilities.setCellsAlignment(jTablePredstaveniVysledkyVyhledavani, SwingConstants.CENTER);
        performed_querry_predstaveni_vyhledavani = sqlidFilm_less;
    }//GEN-LAST:event_jButtonPredstaveniVyhledavaniidFilmJeMensiActionPerformed

    private void jButtonPredstaveniVyhledavavniOdstranitVysledkyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPredstaveniVyhledavavniOdstranitVysledkyActionPerformed
        HelperMethods.clearTableWithVyhledavaniDatTableModel(jTablePredstaveniVysledkyVyhledavani, SQLDOTAZ_PREDSTAVENI);
    }//GEN-LAST:event_jButtonPredstaveniVyhledavavniOdstranitVysledkyActionPerformed

   
    private void jButtonPredstaveniVyhledavaniVymazatVybraneVysledkyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPredstaveniVyhledavaniVymazatVybraneVysledkyActionPerformed
        int[] row = jTablePredstaveniVysledkyVyhledavani.getSelectedRows();
        for (int i = 0; i < row.length; i++) {
           String sqldotaz_delete = PrepareStatement.DeleteSelectedRows(namesofDTBtables[0], namesofcolumns_predstavenitable[0], jTablePredstaveniVysledkyVyhledavani.getModel().getValueAt(i, 0));
         //   String sqldotaz_delete = "DELETE FROM predstaveni WHERE idPredstaveni=" + jTablePredstaveniVysledkyVyhledavani.getModel().getValueAt(i, 0) + ";";
         System.out.println(sqldotaz_delete);  
         executeStatement(sqldotaz_delete);
        }
        HelperMethods.updateTableWithVyhledavaniDatTableModel(jTablePredstaveniVysledkyVyhledavani, performed_querry_predstaveni_vyhledavani);
        HelperMethods.updateTableWithVyhledavaniDatTableModel(jTablePredstaveniDatafromDTB, SQLDOTAZ_PREDSTAVENI);
        //.setColumnWidths(jTablePredstaveniDatafromDTB, 95, 150, 50);
    }//GEN-LAST:event_jButtonPredstaveniVyhledavaniVymazatVybraneVysledkyActionPerformed

    private void jButtonPredstaveniUpravitPopisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPredstaveniUpravitPopisActionPerformed
        if (jTablePredstaveniZobrazenivybranychDat.getSelectedColumn() == jTablePredstaveniZobrazenivybranychDat.getColumnCount() - 1) {
            predstaveni_popis_filmu_selectedrow_index = jTablePredstaveniZobrazenivybranychDat.getSelectedRow();
            predstaveni_popis_filmu_selectedcolumn_index = jTablePredstaveniZobrazenivybranychDat.getSelectedColumn();
            jTextAreaPredstaveniUpravaPopisuFilmu.setText(jTablePredstaveniZobrazenivybranychDat.getValueAt(jTablePredstaveniZobrazenivybranychDat.getSelectedRow(),
                    jTablePredstaveniZobrazenivybranychDat.getSelectedColumn()).toString());
        }
    }//GEN-LAST:event_jButtonPredstaveniUpravitPopisActionPerformed

    private void jButtonPredstaveniPopisFilmuDoTabulkyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPredstaveniPopisFilmuDoTabulkyActionPerformed
        jTablePredstaveniZobrazenivybranychDat.setValueAt(jTextAreaPredstaveniUpravaPopisuFilmu.getText(), predstaveni_popis_filmu_selectedrow_index,
                predstaveni_popis_filmu_selectedcolumn_index);
        jTablePredstaveniZobrazenivybranychDat.repaint(50);
        //System.out.println(jTextAreaPredstaveniUpravaPopisuFilmu.getText());
        //System.out.println(predstaveni_popis_filmu_selectedrow_index);
        // System.out.println(predstaveni_popis_filmu_selectedcolumn_index);
    }//GEN-LAST:event_jButtonPredstaveniPopisFilmuDoTabulkyActionPerformed

    private void jButtonPredstaveniUpravenyPopisAktualizovatVDTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPredstaveniUpravenyPopisAktualizovatVDTBActionPerformed
        String columnname = jTablePredstaveniZobrazenivybranychDat.getColumnName(predstaveni_popis_filmu_selectedcolumn_index);
        String sql_dotaz = "UPDATE film SET " + columnname + "=" + "\"" + jTextAreaPredstaveniUpravaPopisuFilmu.getText() + "\" " + "WHERE film.idFilm=" + "\"" + jTablePredstaveniZobrazenivybranychDat.getValueAt(predstaveni_popis_filmu_selectedrow_index, 0) + "\"" + ";";
        executeStatement(sql_dotaz);
        jTablePredstaveniZobrazenivybranychDat.setModel(new UpravaDatTableModel(performed_querry_predstaveni_film_by_date, 1));
        JTableUtilities.setCellsAlignment(jTablePredstaveniZobrazenivybranychDat, SwingConstants.CENTER);
        HelperMethods.updateDisplayedDataInTableWithZobrazeniDatTableModel(jTablePredstaveniDatafromDTB, SQLDOTAZ_PREDSTAVENI);
    }//GEN-LAST:event_jButtonPredstaveniUpravenyPopisAktualizovatVDTBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameJedenSvet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameJedenSvet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameJedenSvet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameJedenSvet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JFrameJedenSvet jf = new JFrameJedenSvet();
                jf.pack();
                jf.setLocationRelativeTo(null);
                jf.setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFilmAktualizujVDTB;
    private javax.swing.JButton jButtonFilmVyberData;
    private javax.swing.JButton jButtonPredstaveniAktualizujVDTB;
    private javax.swing.JButton jButtonPredstaveniPopisFilmuDoTabulky;
    private javax.swing.JButton jButtonPredstaveniPridatData;
    private javax.swing.JButton jButtonPredstaveniUpravenyPopisAktualizovatVDTB;
    private javax.swing.JButton jButtonPredstaveniUpravitPopis;
    private javax.swing.JButton jButtonPredstaveniVyberData;
    private javax.swing.JButton jButtonPredstaveniVyhledavaniDatumJeMensi;
    private javax.swing.JButton jButtonPredstaveniVyhledavaniDatumJeRovno;
    private javax.swing.JButton jButtonPredstaveniVyhledavaniDatumJeVetsi;
    private javax.swing.JButton jButtonPredstaveniVyhledavaniVymazatVybraneVysledky;
    private javax.swing.JButton jButtonPredstaveniVyhledavaniidFilmJeMensi;
    private javax.swing.JButton jButtonPredstaveniVyhledavaniidFilmuJeRovno;
    private javax.swing.JButton jButtonPredstaveniVyhledavaniidFilmuJeVetsi;
    private javax.swing.JButton jButtonPredstaveniVyhledavaniidPredstaveniJeMensi;
    private javax.swing.JButton jButtonPredstaveniVyhledavaniidPredstaveniJeRovno;
    private javax.swing.JButton jButtonPredstaveniVyhledavaniidPredstaveniJeVetsi;
    private javax.swing.JButton jButtonPredstaveniVyhledavavniOdstranitVysledky;
    private javax.swing.JLabel jLabelFilmDatavDTB;
    private javax.swing.JLabel jLabelFilmPopisAktualizace;
    private javax.swing.JLabel jLabelPredstaveniDatavDTB;
    private javax.swing.JLabel jLabelPredstaveniPopisAktualizace;
    private javax.swing.JLabel jLabelPredstaveniPridaniDat;
    private javax.swing.JLabel jLabelPredstaveniUparavaPopisFilmu;
    private javax.swing.JLabel jLabelPredstaveniVyhledaniPodleidPredstaveni;
    private javax.swing.JLabel jLabelPredstaveniVyhledavaniPopisVolby;
    private javax.swing.JLabel jLabelPredstaveniVyhledavaniVysledky;
    private javax.swing.JLabel jLabelPredstaveniVyhledavaniidFilmu;
    private javax.swing.JLabel jLabelPredstaverniVyhledavaniDatum;
    private javax.swing.JPanel jPanelFilmHlavni;
    private javax.swing.JPanel jPanelFilmPridavaniDat;
    private javax.swing.JPanel jPanelFilmUpravaDat;
    private javax.swing.JPanel jPanelFilmVyhledavaniDat;
    private javax.swing.JPanel jPanelKinoHlavni;
    private javax.swing.JPanel jPanelPredstaveniHlavni;
    private javax.swing.JPanel jPanelPredstaveniPridavaniDat;
    private javax.swing.JPanel jPanelPredstaveniUpravaDat;
    private javax.swing.JPanel jPanelPredstaveniVyhledavaniDat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSpinner jSpinnerPredstaveniVyhledavaniidFilm;
    private javax.swing.JSpinner jSpinnerPredstaveniVyhledavaniidPredstaveni;
    private javax.swing.JTabbedPane jTabbedPaneFilmVnoreny;
    private javax.swing.JTabbedPane jTabbedPanePredstaveniVnoreny;
    private javax.swing.JTabbedPane jTabbedPaneSpolecny;
    private javax.swing.JTable jTableFilmDataFromDTB;
    private javax.swing.JTable jTableFilmZobrazeniVybranychDat;
    private javax.swing.JTable jTablePredstaveniDatafromDTB;
    private javax.swing.JTable jTablePredstaveniPridaniDat;
    private javax.swing.JTable jTablePredstaveniVysledkyVyhledavani;
    private javax.swing.JTable jTablePredstaveniZobrazenivybranychDat;
    private javax.swing.JTextArea jTextAreaPredstaveniUpravaPopisuFilmu;
    private javax.swing.JTextField jTextFieldPredstaveniVyhledavaniDatum;
    // End of variables declaration//GEN-END:variables
}
